'use client';

import { useMemo } from 'react';
import type { SystemMetrics } from '@/types';

/**
 * Derives formatted system metric values from raw SystemMetrics.
 * (The actual data is generated by useProcessSimulation; this hook
 * provides convenience computed values and chart-ready data.)
 */
export interface UseSystemMetricsReturn {
  cpuChartData: { time: number; value: number }[];
  networkUpChartData: { time: number; value: number }[];
  networkDownChartData: { time: number; value: number }[];
  memoryPercent: number;
  swapPercent: number;
  coreChartData: { core: string; value: number }[];
}

export function useSystemMetrics(metrics: SystemMetrics): UseSystemMetricsReturn {
  const cpuChartData = useMemo(
    () => metrics.cpuHistory.map((value, i) => ({ time: i, value: Math.round(value * 10) / 10 })),
    [metrics.cpuHistory]
  );

  const networkUpChartData = useMemo(
    () => metrics.networkUpHistory.map((value, i) => ({ time: i, value: Math.round(value) })),
    [metrics.networkUpHistory]
  );

  const networkDownChartData = useMemo(
    () => metrics.networkDownHistory.map((value, i) => ({ time: i, value: Math.round(value) })),
    [metrics.networkDownHistory]
  );

  const memoryPercent = useMemo(
    () => Math.round((metrics.memoryUsedGB / metrics.memoryTotalGB) * 1000) / 10,
    [metrics.memoryUsedGB, metrics.memoryTotalGB]
  );

  const swapPercent = useMemo(
    () => Math.round((metrics.swapUsedGB / metrics.swapTotalGB) * 1000) / 10,
    [metrics.swapUsedGB, metrics.swapTotalGB]
  );

  const coreChartData = useMemo(
    () => metrics.cpuCores.map((value, i) => ({ core: `Core ${i}`, value: Math.round(value * 10) / 10 })),
    [metrics.cpuCores]
  );

  return {
    cpuChartData,
    networkUpChartData,
    networkDownChartData,
    memoryPercent,
    swapPercent,
    coreChartData,
  };
}
